### ISSUE TITLE
Choose an evaluation suite

### ISSUE THREAD

**Issue by dvanhorn** [davdar/maam#14]
What are we going to show for the empirical evaluation?  We should pick some set of programs (Scheme, Haskell, etc.) and target that.

**Comment by dvanhorn** [comment]
Current top contender:

Modular, Higher-Order Cardinality Analysis in Theory and Practice, POPL 2014.  [paper](http://ilyasergey.net/papers/cardinality-extended.pdf), [slides](http://ilyasergey.net/slides/2014-POPL-Sergey-al.pdf)

**Comment by davdar** [comment]
We decided to punt on a rigorous evaluations section for the paper.
