### ISSUE TITLE
Related work: cite for monad transfomer

### ISSUE THREAD

**Issue by dvanhorn** [davdar/maam#8]
The Liang et al paper cites a TR by Moggi for suggesting monad transformers.  Is that the right cite (I took a quick look and he doesn't use that term, which isn't to say the idea isn't there...)

**Comment by davdar** [comment]
This TR is already the cite for Moggi for which we attribute "pioneering the application of monads to programming language semantics".

**Comment by dvanhorn** [comment]
On 3/24/15 5:13 PM, davdar wrote:
> This TR is already the cite for Moggi for which we attribute "pioneering
> the application of monads to programming language semantics".

That's monads.  Is there a different cite for monad *transformers*?

David

**Comment by davdar** [comment]
Yeah, the original credit to transformers goes to Moggi, and credit to Liang et al for popularizing them.

I just pushed another edit. The text now reads:

This work is inspired by the combination of Cousot and Cousot’s theory of abstract interpretation based on Galois connections [1999, 1977, 1979], Moggi’s original monad transformers [1989] which were later popularized in Liang et al.’s monad transformers for modular interpreters [1995], and Sergey et al.’s monadic abstract interpreters [2013], and continues in the tradition of applying monads to program- ming language semantics pioneered by Moggi [16].
