### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by mrb** [davdar/maam#9]
Having a hard time getting this to build/run - a git clone and then a `make build` doesn't do it. After `cabal install`'ing LambdaJS, things get closer, but not all the way there. Am I missing something obvious?

**Comment by davdar** [comment]
The project doesn't depend on LambdaJS anymore and is rather self contained. Are you up to date with the latest commit on master?

**Comment by mrb** [comment]
@davdar Thank you for the prompt response! My apologies, I was behind a few commits - I didn't expect things to change within a few weeks! Thanks for this work, I'm digging in now and the build works fine. Closing the issue.
